# Generated by Django 4.0.1 on 2022-01-30 15:36

import birthday.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Username')),
                ('user_fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('user_lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('user_college', models.CharField(choices=[('CAUP', 'CAUP'), ('CEduc', 'CEduc'), ('CET', 'CET'), ('CHASS', 'CHASS'), ('Medicine', 'Medicine'), ('Nursing', 'Nursing'), ('PT', 'PT'), ('CS', 'CS'), ('Law', 'Law')], default='CET', max_length=10, verbose_name='College')),
                ('user_year', models.IntegerField(verbose_name='Year')),
                ('user_course', models.CharField(max_length=200, verbose_name='Course')),
                ('user_address', models.CharField(max_length=200, verbose_name='Address')),
                ('user_gender', models.CharField(max_length=100, verbose_name='Gender')),
                ('user_contactnumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('user_birthdate_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('user_birthdate', birthday.fields.BirthdayField()),
            ],
        ),
    ]
