# Generated by Django 4.0.1 on 2022-01-30 16:44

import birthday.fields
from django.db import migrations, models
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=users.models.image_path, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_birthdate',
            field=birthday.fields.BirthdayField(verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_college',
            field=models.CharField(choices=[('CAUP', 'CAUP'), ('Education', 'Education'), ('CET', 'CET'), ('CHASS', 'CHASS'), ('Medicine', 'Medicine'), ('Nursing', 'Nursing'), ('PT', 'PT'), ('CS', 'CS'), ('Law', 'Law')], default='CET', max_length=10, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_contactnumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact Number'),
        ),
    ]
