# Generated by Django 4.0.1 on 2022-01-31 06:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_image_alter_user_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/default_profile_image.jpg', upload_to=users.models.image_path, verbose_name='Profile Picture'),
        ),
    ]
