# Generated by Django 4.0.1 on 2022-02-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_birthdate_dayofyear_internal',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_birthdate',
            field=models.DateField(verbose_name='Birthdate'),
        ),
    ]
