# Generated by Django 4.0.1 on 2022-02-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_username_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='usname',
        ),
    ]
