# Generated by Django 4.0.1 on 2022-02-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_user_name_user_usname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usname',
            field=models.CharField(max_length=200, unique=True, verbose_name='Usname'),
        ),
    ]
