# Generated by Django 4.0.1 on 2022-02-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_users_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
