# Generated by Django 4.0.1 on 2022-02-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usname',
        ),
    ]
