# Generated by Django 4.0.1 on 2022-02-05 05:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_usname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_code', models.CharField(max_length=10, unique=True, verbose_name='Product Code')),
                ('pro_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('pro_category', models.CharField(choices=[('Filing Supplies', 'Filing Supplies'), ('School and Office Essentials', 'School and Office Essentials'), ('Writing Supplies', 'Writing Supplies'), ('Paper Supplies', 'Paper Supplies'), ('Books', 'Books'), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=100, verbose_name='Category')),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('pro_quantity', models.IntegerField(verbose_name='Stocks Left')),
                ('pro_sold', models.IntegerField(verbose_name='Quantity Sold')),
                ('pro_totalsales', models.IntegerField(verbose_name='Total Sale')),
                ('pro_image', models.ImageField(default='supplies/placeholder.jpg', upload_to=users.models.pro_image_path, verbose_name='Product Image')),
            ],
        ),
    ]
