# Generated by Django 4.0.1 on 2022-02-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_college',
            field=models.CharField(choices=[('CAUP', 'CAUP'), ('Education', 'Education'), ('CET', 'CET'), ('CHASS', 'CHASS'), ('Medicine', 'Medicine'), ('Nursing', 'Nursing'), ('PT', 'PT'), ('CS', 'CS'), ('Law', 'Law'), ('N/A', 'N/A')], default='N/A', max_length=10, verbose_name='College'),
        ),
    ]
