# Generated by Django 4.0.1 on 2022-02-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_user_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='pro_sold',
            field=models.IntegerField(blank=True, verbose_name='Quantity Sold'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='pro_totalsales',
            field=models.IntegerField(blank=True, verbose_name='Total Sale'),
        ),
    ]
