# Generated by Django 4.0.1 on 2022-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_inventory_pro_totalsold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='pro_totalsold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Qty Sold'),
        ),
    ]
